const DevicesData = () => {
  const devices = [
    {
      id: 39,
      name: "Devices",
      url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/Category/c5c2ceec-ddfd-4c9f-bc3d-e3f95c9fcba4.png",
      webBgUrl: null,
      mobileBgUrl: null,
      mainCategoryId: 8,
      isCustomCategory: false,
      productListBuyers: [
        {
          productId: 105,
          productTypeId: 1,
          url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/a9e5611b-4d6c-4317-8922-d7e4ff00cb52..jpg",
          name: "Silver Grey",
          originalPrice: 29000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: true,
          createdDate: "2023-06-07T10:04:44.8378732",
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 2,
          totalOrder: 1,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 99,
          firstSkuValue: "Default",
          firstSkuId: 1,
        },
        {
          productId: 104,
          productTypeId: 1,
          url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/764a1f7b-8586-403d-bbbd-7cbae6295fdd..jpg",
          name: "Light Yellow",
          originalPrice: 29000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: true,
          createdDate: "2023-06-07T09:34:53.4032166",
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 1,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: "Default",
          firstSkuId: 1,
        },
        {
          productId: 103,
          productTypeId: 1,
          url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/e20eb384-d22f-46cb-8bd5-f45fbc21d9a9..jpg",
          name: "Candy Blue",
          originalPrice: 29000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: true,
          createdDate: "2023-06-06T16:43:05.4998628",
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 20,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: "Default",
          firstSkuId: 1,
        },
        {
          productId: 68,
          productTypeId: 1,
          url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/39ebda26-f8e9-4ecb-b287-ba1e55223d7f..jpg",
          name: "Wild Green Device",
          originalPrice: 29000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: true,
          createdDate: "2023-03-30T15:23:09.1733303",
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 1,
          totalOrder: 112,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 80,
          firstSkuValue: "Default",
          firstSkuId: 1,
        },
        {
          productId: 67,
          productTypeId: 1,
          url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/e091793a-99bd-48ec-a187-a2139f2249c9..jpg",
          name: "Sky Black ",
          originalPrice: 29000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: true,
          createdDate: "2023-03-30T15:21:29.0949614",
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 100,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: "Default",
          firstSkuId: 1,
        },
        {
          productId: 66,
          productTypeId: 1,
          url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/287506f0-fb1a-4ef7-ac3f-3945c4981999..jpg",
          name: "Cloud White",
          originalPrice: 29000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: true,
          createdDate: "2023-03-30T10:15:16.0158125",
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 1,
          totalOrder: 120,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: "Default",
          firstSkuId: 1,
        },
      ],
    },
    {
      id: 65,
      name: "Pods",
      url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/Category/a5f23e97-369b-48c5-a1e2-a10c284f07c4.png",
      webBgUrl: null,
      mobileBgUrl: null,
      mainCategoryId: 18,
      isCustomCategory: false,
      productListBuyers: [
        {
          productId: 91,
          productTypeId: 1,
          url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/f1c87879-f735-4e99-ac77-6f2562ff2079..jpg",
          name: "Blueberry Cyclone",
          originalPrice: 8000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: "2023-04-03T16:27:00.9319442",
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 1,
          totalOrder: 113,
          skuValueSize: 2,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: "Nicotine3%",
          firstSkuId: 1,
        },
        {
          productId: 82,
          productTypeId: 1,
          url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/0ff4b8e4-192b-4a23-9788-1f1679508b43..jpg",
          name: "Strawberry ",
          originalPrice: 8000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: "2023-03-30T16:40:10.4668533",
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 25,
          skuValueSize: 2,
          leftQtyForFirstSkuValue: 85,
          firstSkuValue: "Nicotine3%",
          firstSkuId: 1,
        },
        {
          productId: 81,
          productTypeId: 1,
          url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/5dde39ac-2821-4062-aea3-a4e6ee9fdfc2..jpg",
          name: "Sparkling ",
          originalPrice: 8000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: "2023-03-30T16:37:08.1992339",
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 19,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 82,
          firstSkuValue: "Nicotine5%",
          firstSkuId: 1,
        },
        {
          productId: 80,
          productTypeId: 1,
          url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/a0f2feea-0a0b-4e14-a5ea-6e3214a21313..jpg",
          name: "Sanqi Power ",
          originalPrice: 8000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: "2023-03-30T16:36:08.9398886",
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 0,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: "Nicotine0%",
          firstSkuId: 1,
        },
        {
          productId: 79,
          productTypeId: 1,
          url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/1338e73d-9dc7-4c78-b74f-c21488e893d2..jpg",
          name: "Refreshing Mint ",
          originalPrice: 8000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: "2023-03-30T16:34:38.2124385",
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 0,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: "Nicotine5%",
          firstSkuId: 1,
        },
        {
          productId: 78,
          productTypeId: 1,
          url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/55acb15b-ab5a-4665-bf05-83a20fd813ae..jpg",
          name: "Pummelo Peel ",
          originalPrice: 8000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: "2023-03-30T16:33:31.2971711",
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 0,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: "Nicotine0%",
          firstSkuId: 1,
        },
        {
          productId: 77,
          productTypeId: 1,
          url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/c945f70d-e47c-41d0-a282-0e5ef7ec580f..jpg",
          name: "Pineapple ",
          originalPrice: 8000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: "2023-03-30T16:32:25.4385479",
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 1,
          skuValueSize: 2,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: "Nicotine3%,Nicotine5%",
          firstSkuId: 1,
        },
        {
          productId: 76,
          productTypeId: 1,
          url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/79102d8b-c001-40fd-9f93-a72942d3f485..jpg",
          name: "Lychee Rose ",
          originalPrice: 8000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: "2023-03-30T16:31:13.667124",
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 2,
          totalOrder: 2,
          skuValueSize: 2,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: "Nocotine5%",
          firstSkuId: 1,
        },
        {
          productId: 75,
          productTypeId: 1,
          url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/61edf569-6449-4b91-9999-b6c47e3e661d..jpg",
          name: "Lemongrass Herb ",
          originalPrice: 8000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: "2023-03-30T16:30:10.9000128",
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 0,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: "Nicotine5%",
          firstSkuId: 1,
        },
        {
          productId: 74,
          productTypeId: 1,
          url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/efabf89f-b0ac-4760-8bac-4f87579ca6ad..jpg",
          name: "Kiwi Sour ",
          originalPrice: 8000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: "2023-03-30T16:29:00.4580087",
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 0,
          skuValueSize: 2,
          leftQtyForFirstSkuValue: 200,
          firstSkuValue: "Nicotine3%",
          firstSkuId: 1,
        },
        {
          productId: 73,
          productTypeId: 1,
          url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/ea487fb1-12cf-45e0-93d8-0b7aa0dfa30e..jpg",
          name: "Coke Holic ",
          originalPrice: 8000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: "2023-03-30T16:27:42.9362729",
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 0,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: "Nicotine5%",
          firstSkuId: 1,
        },
        {
          productId: 72,
          productTypeId: 1,
          url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/dad4cf7c-d0c1-4484-b591-e356453b8044..jpg",
          name: "Clove Aroma ",
          originalPrice: 8000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: "2023-03-30T16:26:27.755145",
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 0,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: "Default",
          firstSkuId: 1,
        },
        {
          productId: 71,
          productTypeId: 1,
          url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/c0b1d606-8e5b-4b54-8bb9-c62605d886f4..jpg",
          name: "Citrus Monster ",
          originalPrice: 8000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: "2023-03-30T16:23:43.9770268",
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 1,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: "Nicotine5%",
          firstSkuId: 1,
        },
      ],
    },
    {
      id: 66,
      name: "Disposables",
      url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/Category/5213e417-d74b-48d3-b159-9f61097b61b7.png",
      webBgUrl: null,
      mobileBgUrl: null,
      mainCategoryId: 19,
      isCustomCategory: false,
      productListBuyers: [
        {
          productId: 121,
          productTypeId: 1,
          url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/99dfb493-082a-4b18-b8e6-927fee6795d7..jpg",
          name: "Mixed Peach & Guava",
          originalPrice: 23000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: "2023-06-07T11:25:23.713492",
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 3,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: "2%",
          firstSkuId: 1,
        },
        {
          productId: 120,
          productTypeId: 1,
          url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/e1d47eaf-5e78-4dba-a377-0a9b1f1885e1..jpg",
          name: "Mango Summer",
          originalPrice: 23000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: "2023-06-07T11:22:28.579439",
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 16,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 99,
          firstSkuValue: "2%",
          firstSkuId: 1,
        },
        {
          productId: 119,
          productTypeId: 1,
          url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/7ea2938c-e1b1-40cd-af46-846ee6f3eb4f..jpg",
          name: "Strawberry Strike",
          originalPrice: 23000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: "2023-06-07T11:20:15.7426797",
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 0,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: "2%",
          firstSkuId: 1,
        },
        {
          productId: 118,
          productTypeId: 1,
          url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/0f7774a0-ae80-4a95-a516-1dfe1902e0fa..jpg",
          name: "Citrus Monster",
          originalPrice: 23000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: "2023-06-07T11:18:45.9323376",
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 0,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: "2%",
          firstSkuId: 1,
        },
        {
          productId: 117,
          productTypeId: 1,
          url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/8d0b30ec-39a8-4764-a841-ed73de260f4b..jpg",
          name: "Pinapple Splash",
          originalPrice: 23000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: "2023-06-07T11:17:32.8064621",
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 0,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: "2%",
          firstSkuId: 1,
        },
        {
          productId: 116,
          productTypeId: 1,
          url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/ab5523a3-35d7-4885-b318-3922ce7dcdf2..jpg",
          name: "Iced Grapes",
          originalPrice: 17500,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: "2023-06-07T11:03:22.1718462",
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 1,
          totalOrder: 2,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: "3%",
          firstSkuId: 2,
        },
        {
          productId: 115,
          productTypeId: 1,
          url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/adc619c1-3a49-4129-8f49-d82b33a04aaa..jpg",
          name: "Chilled Watermelon ",
          originalPrice: 17500,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: "2023-06-07T11:02:13.5123867",
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 1,
          totalOrder: 2,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 99,
          firstSkuValue: "3%",
          firstSkuId: 2,
        },
        {
          productId: 114,
          productTypeId: 1,
          url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/e754bd80-a032-4435-beef-9585f85d5928..jpg",
          name: "Strawberry Strike",
          originalPrice: 17500,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: "2023-06-07T10:59:40.9575367",
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 0,
          skuValueSize: 2,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: "3%",
          firstSkuId: 2,
        },
        {
          productId: 113,
          productTypeId: 1,
          url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/daadafed-5a41-4fda-bfae-ac21356012ff..jpg",
          name: "Sparkling Sarsae",
          originalPrice: 17500,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: "2023-06-07T10:57:37.12852",
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 1,
          totalOrder: 1,
          skuValueSize: 3,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: "0%",
          firstSkuId: 1,
        },
        {
          productId: 112,
          productTypeId: 1,
          url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/22530916-d7ca-4298-8e9e-d001b951afb4..jpg",
          name: "Refreshing Mint",
          originalPrice: 17500,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: "2023-06-07T10:55:43.7984909",
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 0,
          skuValueSize: 3,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: "0%",
          firstSkuId: 1,
        },
        {
          productId: 111,
          productTypeId: 1,
          url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/2d0f65c8-2ede-40d8-ac20-114e04b57ca2..jpg",
          name: "Pineapple Splash",
          originalPrice: 17500,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: "2023-06-07T10:51:25.9493155",
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 0,
          skuValueSize: 3,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: "0%",
          firstSkuId: 1,
        },
        {
          productId: 110,
          productTypeId: 1,
          url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/beb598fd-cb8a-4c92-946f-5eadcd92f6f7..jpg",
          name: "Lychee Rose",
          originalPrice: 17500,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: "2023-06-07T10:49:33.4852246",
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 15,
          skuValueSize: 3,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: "0%",
          firstSkuId: 1,
        },
        {
          productId: 109,
          productTypeId: 1,
          url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/57e569e6-d61b-454f-bbc9-92e010a585e0..jpg",
          name: "Kiwi Sour",
          originalPrice: 17500,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: "2023-06-07T10:40:08.2865678",
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 0,
          skuValueSize: 3,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: "0%",
          firstSkuId: 1,
        },
        {
          productId: 108,
          productTypeId: 1,
          url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/ccf4d9a7-d966-4f90-8c4e-b46b604466bb..jpg",
          name: "Citrus Monster",
          originalPrice: 17500,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: "2023-06-07T10:38:36.3315583",
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 1,
          totalOrder: 0,
          skuValueSize: 3,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: "0%",
          firstSkuId: 1,
        },
        {
          productId: 107,
          productTypeId: 1,
          url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/0b042200-6b91-4fed-925d-9eaa4f44a2ad..jpg",
          name: "Blueberry",
          originalPrice: 17500,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: "2023-06-07T10:32:09.8245196",
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 0,
          skuValueSize: 3,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: "0%",
          firstSkuId: 1,
        },
        {
          productId: 106,
          productTypeId: 1,
          url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/78768f20-ef2f-47b4-a49c-e53a83279d33..jpg",
          name: "Cokeholic",
          originalPrice: 17500,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: "2023-06-07T10:16:30.35753",
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 0,
          skuValueSize: 3,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: "0%",
          firstSkuId: 1,
        },
        {
          productId: 90,
          productTypeId: 1,
          url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/c7b7cee9-dbeb-4f98-964b-681dceec0ae5..jpg",
          name: "Strawberry ",
          originalPrice: 10000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: "2023-03-31T09:25:19.6666532",
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 4,
          skuValueSize: 2,
          leftQtyForFirstSkuValue: 0,
          firstSkuValue: "Nicotine3%,Nicotine5%",
          firstSkuId: 1,
        },
        {
          productId: 89,
          productTypeId: 1,
          url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/d7334bd5-3bf7-4c1a-84c2-af3e420d0652..jpg",
          name: "Sparkling ",
          originalPrice: 10000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: "2023-03-31T09:23:08.110818",
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 54,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: "Nicotine5%",
          firstSkuId: 1,
        },
        {
          productId: 87,
          productTypeId: 1,
          url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/106cd644-0d30-44aa-a58e-8075486e621e..jpg",
          name: "Pineapple ",
          originalPrice: 10000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: "2023-03-31T09:19:32.2613098",
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 0,
          skuValueSize: 2,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: "Nicotine3%,Nicotine5%",
          firstSkuId: 1,
        },
        {
          productId: 86,
          productTypeId: 1,
          url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/7609cdc4-503d-471f-b093-4da41fad9b10..jpg",
          name: "Lychee Rose ",
          originalPrice: 10000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: "2023-03-31T09:18:20.1840605",
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 0,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: "Nicotine5%",
          firstSkuId: 1,
        },
        {
          productId: 85,
          productTypeId: 1,
          url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/5ec3f72b-3995-4755-bbe2-c9f4ed22c5d5..jpg",
          name: "Kiwi Sour ",
          originalPrice: 10000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: "2023-03-31T09:16:59.364801",
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 0,
          skuValueSize: 2,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: "Nicotine3%",
          firstSkuId: 1,
        },
        {
          productId: 84,
          productTypeId: 1,
          url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/52268ea6-3721-40ed-9262-46a67e84b2f9..jpg",
          name: "Cokeholic ",
          originalPrice: 10000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: "2023-03-31T09:15:38.037369",
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 0,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 200,
          firstSkuValue: "Nicotine5%",
          firstSkuId: 1,
        },
        {
          productId: 83,
          productTypeId: 1,
          url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/be91ea49-9cd9-4c1a-9d52-916c39bc9622..jpg",
          name: "Citrus Monster ",
          originalPrice: 10000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: "2023-03-31T09:13:25.4540735",
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 2,
          skuValueSize: 1,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: "Nicotine5%",
          firstSkuId: 1,
        },
        {
          productId: 69,
          productTypeId: 1,
          url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/8e4b0efc-52f7-4e4b-8aa1-1be8112ddd71..jpg",
          name: "Blueberry ",
          originalPrice: 10000,
          promotePrice: 0,
          promotePercent: 0,
          isFav: false,
          isGetOne: false,
          createdDate: "2023-03-30T15:33:53.1013225",
          fromPrice: 0,
          toPrice: 0,
          hasFromToPrice: false,
          promoteFromPrice: null,
          promoteToPrice: null,
          totalWishList: 0,
          totalOrder: 101,
          skuValueSize: 2,
          leftQtyForFirstSkuValue: 100,
          firstSkuValue: "Nicotine3%",
          firstSkuId: 1,
        },
      ],
    },
    {
      id: 89,
      name: "Pi",
      url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/category/4a4b0fd2-4cc5-4bb0-9f41-ee236362996d.png",
      webBgUrl: null,
      mobileBgUrl: null,
      mainCategoryId: 20,
      isCustomCategory: false,
      productListBuyers: [],
    },
  ];
  const hero = [
    {
      id: 406,
      name: "MobileBanner3",
      url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/0831d529-5bfd-4d23-bd17-9fae54a0612c.png",
      bannerLinkId: 15,
      isWeb: 0,
      brandId: null,
      seqNo: 1,
      width: "1074",
      height: "1440",
      categoryId: null,
      categoryName: null,
      categoryImgUrl: null,
      productId: null,
      productName: null,
      searchKeyword: null,
      recommendedId: null,
    },
    {
      id: 417,
      name: "WebBanner4",
      url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/05111ead-159b-4e56-a4e0-26ca4342044c.png",
      bannerLinkId: 15,
      isWeb: 1,
      brandId: null,
      seqNo: 1,
      width: "1074",
      height: "1440",
      categoryId: null,
      categoryName: null,
      categoryImgUrl: null,
      productId: null,
      productName: null,
      searchKeyword: null,
      recommendedId: null,
    },
    {
      id: 408,
      name: "MobileBanner3",
      url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/4a5d0558-8051-494e-99ef-a25ae33cb0ce.png",
      bannerLinkId: 16,
      isWeb: 0,
      brandId: null,
      seqNo: 2,
      width: "1074",
      height: "1440",
      categoryId: 39,
      categoryName: "Devices",
      categoryImgUrl:
        "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/Category/c5c2ceec-ddfd-4c9f-bc3d-e3f95c9fcba4.png",
      productId: null,
      productName: null,
      searchKeyword: null,
      recommendedId: null,
    },
    {
      id: 416,
      name: "WebBanner3",
      url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/98a83a70-457a-434b-b381-bfbe017e88f3.png",
      bannerLinkId: 16,
      isWeb: 1,
      brandId: null,
      seqNo: 2,
      width: "1074",
      height: "1440",
      categoryId: 39,
      categoryName: "Devices",
      categoryImgUrl:
        "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/Category/c5c2ceec-ddfd-4c9f-bc3d-e3f95c9fcba4.png",
      productId: null,
      productName: null,
      searchKeyword: null,
      recommendedId: null,
    },
    {
      id: 407,
      name: "MobileBanner3",
      url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/47504a5b-dc81-45c5-aa7d-2df90c87345f.png",
      bannerLinkId: 16,
      isWeb: 0,
      brandId: null,
      seqNo: 3,
      width: "1074",
      height: "1440",
      categoryId: 39,
      categoryName: "Devices",
      categoryImgUrl:
        "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/Category/c5c2ceec-ddfd-4c9f-bc3d-e3f95c9fcba4.png",
      productId: null,
      productName: null,
      searchKeyword: null,
      recommendedId: null,
    },
    {
      id: 419,
      name: "WebBanner3",
      url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/28aa2506-eef6-4330-8d45-50e4fd3b0cd1.png",
      bannerLinkId: 16,
      isWeb: 1,
      brandId: null,
      seqNo: 3,
      width: "1074",
      height: "1440",
      categoryId: 39,
      categoryName: "Devices",
      categoryImgUrl:
        "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/Category/c5c2ceec-ddfd-4c9f-bc3d-e3f95c9fcba4.png",
      productId: null,
      productName: null,
      searchKeyword: null,
      recommendedId: null,
    },
    {
      id: 418,
      name: "WebBanner2",
      url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/9b7dcffe-a667-4c8c-b496-30e204159051.png",
      bannerLinkId: 16,
      isWeb: 1,
      brandId: null,
      seqNo: 4,
      width: "1074",
      height: "1440",
      categoryId: 66,
      categoryName: "Disposables",
      categoryImgUrl:
        "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/Category/5213e417-d74b-48d3-b159-9f61097b61b7.png",
      productId: null,
      productName: null,
      searchKeyword: null,
      recommendedId: null,
    },
  ];
  const flavor = [
    {
      id: 396,
      name: "MobileAds3",
      url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/242bde5a-7d83-45ef-9c69-8b5b463196cc.png",
      bannerLinkId: 10,
      isWeb: 0,
      brandId: null,
      seqNo: 1,
      width: "840",
      height: "1080",
      categoryId: null,
      categoryName: null,
      categoryImgUrl: null,
      productId: 115,
      productName: "Chilled Watermelon ",
      searchKeyword: null,
      recommendedId: null,
    },
    {
      id: 401,
      name: "WebAds1",
      url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/a0bbb0b5-8d28-4565-bbe8-3d7142a33ab7.png",
      bannerLinkId: 8,
      isWeb: 1,
      brandId: null,
      seqNo: 1,
      width: "840",
      height: "1080",
      categoryId: 82,
      categoryName: "Cokeholic",
      categoryImgUrl:
        "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/Category/4c7ca7c0-d203-4e2d-9aa8-6701aa829799..png",
      productId: null,
      productName: null,
      searchKeyword: null,
      recommendedId: null,
    },
    {
      id: 402,
      name: "WebAds2",
      url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/6c6f08c3-75ef-4f6f-9b6f-381a5b004ade.png",
      bannerLinkId: 10,
      isWeb: 1,
      brandId: null,
      seqNo: 2,
      width: "840",
      height: "1080",
      categoryId: null,
      categoryName: null,
      categoryImgUrl: null,
      productId: 116,
      productName: "Iced Grapes",
      searchKeyword: null,
      recommendedId: null,
    },
    {
      id: 398,
      name: "MobileAds2",
      url: "https://aws-mhsimages-bucket.s3-ap-southeast-1.amazonaws.com/sit/VapePI/images/product/cd2504ee-7254-4a9d-bf71-d26ae8526273.png",
      bannerLinkId: 10,
      isWeb: 0,
      brandId: null,
      seqNo: 2,
      width: "840",
      height: "1080",
      categoryId: null,
      categoryName: null,
      categoryImgUrl: null,
      productId: 116,
      productName: "Iced Grapes",
      searchKeyword: null,
      recommendedId: null,
    },
  ];
  return {
    devices,
    hero,
    flavor,
  };
};

export default DevicesData;
